hash-format = "sha256"

[[files]]
file = "config/quilt-loader-overrides.json"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Encryption.json"

[[files]]
file = "config/yosbr/config/bigpony.json"

[[files]]
file = "config/yosbr/config/bluemap/core.conf"

[[files]]
file = "config/yosbr/config/bluemap/maps/end.conf"

[[files]]
file = "config/yosbr/config/bluemap/maps/nether.conf"

[[files]]
file = "config/yosbr/config/bluemap/maps/overworld.conf"

[[files]]
file = "config/yosbr/config/bluemap/maps/overworld_10.conf"

[[files]]
file = "config/yosbr/config/bluemap/maps/overworld_11.conf"

[[files]]
file = "config/yosbr/config/bluemap/maps/overworld_12.conf"

[[files]]
file = "config/yosbr/config/bluemap/maps/overworld_13.conf"

[[files]]
file = "config/yosbr/config/bluemap/maps/overworld_14.conf"

[[files]]
file = "config/yosbr/config/bluemap/maps/overworld_15.conf"

[[files]]
file = "config/yosbr/config/bluemap/maps/overworld_16.conf"

[[files]]
file = "config/yosbr/config/bluemap/maps/overworld_2.conf"

[[files]]
file = "config/yosbr/config/bluemap/maps/overworld_3.conf"

[[files]]
file = "config/yosbr/config/bluemap/maps/overworld_4.conf"

[[files]]
file = "config/yosbr/config/bluemap/maps/overworld_5.conf"

[[files]]
file = "config/yosbr/config/bluemap/maps/overworld_6.conf"

[[files]]
file = "config/yosbr/config/bluemap/maps/overworld_7.conf"

[[files]]
file = "config/yosbr/config/bluemap/maps/overworld_8.conf"

[[files]]
file = "config/yosbr/config/bluemap/maps/overworld_9.conf"

[[files]]
file = "config/yosbr/config/bluemap/plugin.conf"

[[files]]
file = "config/yosbr/config/bluemap/storages/file.conf"

[[files]]
file = "config/yosbr/config/bluemap/storages/sql.conf"

[[files]]
file = "config/yosbr/config/bluemap/webapp.conf"

[[files]]
file = "config/yosbr/config/bluemap/webserver.conf"

[[files]]
file = "config/yosbr/config/dimdoors-config.json5"

[[files]]
file = "config/yosbr/config/modmenu.json"

[[files]]
file = "config/yosbr/config/openpartiesandclaims-server.toml"

[[files]]
file = "config/yosbr/config/quilt_loading_screen.json"

[[files]]
file = "config/yosbr/config/servercore/config.yml"

[[files]]
file = "config/yosbr/config/servercore/optimizations.yml"

[[files]]
file = "config/yosbr/config/styled-nicknames.json"

[[files]]
file = "config/yosbr/config/universal-graves/config.json"

[[files]]
file = "config/yosbr/options.txt"

[[files]]
file = "mods/ad-astra.pw.toml"
metafile = true

[[files]]
file = "mods/adorn.pw.toml"
metafile = true

[[files]]
file = "mods/ambient-environment.pw.toml"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/audioplayer.pw.toml"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
metafile = true

[[files]]
file = "mods/bellsandwhistles.pw.toml"
metafile = true

[[files]]
file = "mods/better-archeology.pw.toml"
metafile = true

[[files]]
file = "mods/big-pony.pw.toml"
metafile = true

[[files]]
file = "mods/bits-and-chisels.pw.toml"
metafile = true

[[files]]
file = "mods/blockus.pw.toml"
metafile = true

[[files]]
file = "mods/bluemap.pw.toml"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
metafile = true

[[files]]
file = "mods/cccbridge.pw.toml"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
metafile = true

[[files]]
file = "mods/clear-void.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
metafile = true

[[files]]
file = "mods/computer-cartographer.pw.toml"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
metafile = true

[[files]]
file = "mods/create-air-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/create-deco.pw.toml"
metafile = true

[[files]]
file = "mods/create-diesel-generators-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/create-enchantment-industry-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/create-garnished.pw.toml"
metafile = true

[[files]]
file = "mods/create-goggles.pw.toml"
metafile = true

[[files]]
file = "mods/create-new-age.pw.toml"
metafile = true

[[files]]
file = "mods/create-ore-excavation.pw.toml"
metafile = true

[[files]]
file = "mods/create-power-loader-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
metafile = true

[[files]]
file = "mods/create-structures.pw.toml"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
metafile = true

[[files]]
file = "mods/dark-loading-screen.pw.toml"
metafile = true

[[files]]
file = "mods/dawn.pw.toml"
metafile = true

[[files]]
file = "mods/dimensionaldoors.pw.toml"
metafile = true

[[files]]
file = "mods/double-doors.pw.toml"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
metafile = true

[[files]]
file = "mods/effective.pw.toml"
metafile = true

[[files]]
file = "mods/emi-loot.pw.toml"
metafile = true

[[files]]
file = "mods/emi-ores.pw.toml"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
metafile = true

[[files]]
file = "mods/emiffect.pw.toml"
metafile = true

[[files]]
file = "mods/emitrades.pw.toml"
metafile = true

[[files]]
file = "mods/endrem.pw.toml"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/expanded-storage.pw.toml"
metafile = true

[[files]]
file = "mods/explosive-enhancement.pw.toml"
metafile = true

[[files]]
file = "mods/extended-cogwheels.pw.toml"
metafile = true

[[files]]
file = "mods/extra-mod-integrations.pw.toml"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
metafile = true

[[files]]
file = "mods/fallingtree.pw.toml"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/fix-keyboard-on-linux.pw.toml"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
metafile = true

[[files]]
file = "mods/geode-plus.pw.toml"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
metafile = true

[[files]]
file = "mods/hd-skins.pw.toml"
metafile = true

[[files]]
file = "mods/htm.pw.toml"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
metafile = true

[[files]]
file = "mods/lambdabettergrass.pw.toml"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
metafile = true

[[files]]
file = "mods/ledger.pw.toml"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-bridges.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-doors.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-fences-and-walls.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-furniture.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-holidays.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-lights-and-lamps.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-paintings.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-paths-and-pavings.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-roofs.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-trapdoors.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-windows.pw.toml"
metafile = true

[[files]]
file = "mods/megane.pw.toml"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
metafile = true

[[files]]
file = "mods/mine-little-pony.pw.toml"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
metafile = true

[[files]]
file = "mods/modern-farlands-mod.pw.toml"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/neruina.pw.toml"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
metafile = true

[[files]]
file = "mods/opac-bluemap-integration.pw.toml"
metafile = true

[[files]]
file = "mods/opac-fabric-create-support.pw.toml"
metafile = true

[[files]]
file = "mods/open-parties-and-claims.pw.toml"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
metafile = true

[[files]]
file = "mods/pehkui.pw.toml"
metafile = true

[[files]]
file = "mods/pick-your-poison.pw.toml"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
metafile = true

[[files]]
file = "mods/qds-magic-mirror.pw.toml"
metafile = true

[[files]]
file = "mods/qkl.pw.toml"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
metafile = true

[[files]]
file = "mods/quilt-loading-screen.pw.toml"
metafile = true

[[files]]
file = "mods/rechiseled-create.pw.toml"
metafile = true

[[files]]
file = "mods/rechiseled.pw.toml"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
metafile = true

[[files]]
file = "mods/satin-api.pw.toml"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
metafile = true

[[files]]
file = "mods/server-country-flags.pw.toml"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
metafile = true

[[files]]
file = "mods/slice-and-dice.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
metafile = true

[[files]]
file = "mods/stackdeobf.pw.toml"
metafile = true

[[files]]
file = "mods/status-effect-bars.pw.toml"
metafile = true

[[files]]
file = "mods/styled-nicknames.pw.toml"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
metafile = true

[[files]]
file = "mods/templates-2.pw.toml"
metafile = true

[[files]]
file = "mods/the-lost-castle.pw.toml"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
metafile = true

[[files]]
file = "mods/timeoutout.pw.toml"
metafile = true

[[files]]
file = "mods/toms-peripherals.pw.toml"
metafile = true

[[files]]
file = "mods/toms-storage.pw.toml"
metafile = true

[[files]]
file = "mods/toms-trading-network.pw.toml"
metafile = true

[[files]]
file = "mods/travelersbackpack.pw.toml"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
metafile = true

[[files]]
file = "mods/unicopia-blockus-addon.pw.toml"
metafile = true

[[files]]
file = "mods/unicopia.pw.toml"
metafile = true

[[files]]
file = "mods/universal-graves.pw.toml"
metafile = true

[[files]]
file = "mods/universal_ores.pw.toml"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/voice-chat-interaction.pw.toml"
metafile = true

[[files]]
file = "mods/waygl.pw.toml"
metafile = true

[[files]]
file = "mods/white_rabbit.pw.toml"
metafile = true

[[files]]
file = "mods/wthit.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-end-island.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-nether-fortresses.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-witch-huts.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-bridges.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-extras.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-menu-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/MineLittlePony-Extra-Pony-Armor-Pack.pw.toml"
metafile = true
