name = "tempproject"
author = "Fauli1221"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "766a3c63323617b05e98b4aed0dc7dbb15225ae9dc255e4e67f221bcdb7901aa"

[versions]
minecraft = "1.20.1"
quilt = "0.24.0-beta.8"
